### ISSUE TITLE
Extend channels list

### ISSUE THREAD

**Issue by shpaker** [ninedraft/awesomeaddmeto#18]
Добавить каналы в `list.yml` и проставить им правильно тег.
Предварительно проревьюить, что в них нет порнографии и чернухи.
ПР нацеливать на ветку `develop`.

* [ ] https://t.me/radiot_comments
* [ ] https://t.me/addmetotravel
* [ ] https://t.me/geekshit
* [ ] https://t.me/big_bad_evil_goldfish
* [ ] https://t.me/happyHEP
* [ ] https://t.me/havka
* [ ] https://t.me/publicpavlik
* [ ] https://t.me/CardanoRussiaAnnouncements

**Comment by valery-kirichenko** [comment]
Говорят, этот канал тоже имеет какое-то отношение к addmeto:
- [x] https://t.me/beta_discovered

**Comment by shpaker** [comment]
* [ ] https://t.me/elidoc0rc

**Comment by shpaker** [comment]
* [ ] https://t.me/popyachsa

**Comment by ninedraft** [comment]
- [ ] https://t.me/bitsofnew
- [ ] https://t.me/teamerlin
