### ISSUE TITLE
Добавить меня коллаборатором

### ISSUE THREAD

**Issue by chuprik** [ninedraft/awesomeaddmeto#6]

**Comment by qqalexqq** [comment]
Is that really necessary? We don't have JS here.

**Comment by chuprik** [comment]
I know PHP ;)

**Comment by shpaker** [comment]
@kotchuprik А если серъёзно, то зачем? Тут мертво - я только развлекаюсь сейчас. Единственное, что можно треша какого в шаблон порисовать. Но надо подождать пока я докручу нормально генерацию ридмишки из шаблона.

**Comment by shpaker** [comment]
@ninedraft давай покрутим настройки репы:

- мне не нравится, что могут на прямую пушить без ПР'ов
- ну и Косте можно прав выписать

**Comment by chuprik** [comment]
Чтоб было :D А так, напиши потом в телеге, что именно ты хочешь сделать )

**Comment by qqalexqq** [comment]
Так себе фича, закрываю за ненужностью
